global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ai-upscaler-api'
    static_configs:
      - targets: ['ai-upscaler-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8081']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
    scrape_interval: 5s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']  # Use redis-exporter instead
    scrape_interval: 5s
